version: '3.8'

services:
  twote-web:
    build:
      context: .
      dockerfile: twote-web/Dockerfile
    ports:
      - "3000:3000"

  envoy-proxy:
    image: envoyproxy/envoy:v1.18.3
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  twote-api:
    build:
      context: .
      dockerfile: twote-api/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./schemas:/usr/src/schemas

  accounts-backend:
    build:
      context: .
      dockerfile: accounts-backend/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./schemas:/usr/src/schemas
    environment:
      DATABASE_URL: "postgres://myuser:mypassword@accounts-db/mydatabase"

  profiles-backend:
    build:
      context: .
      dockerfile: profiles-backend/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./schemas:/usr/src/schemas

  tweets-backend:
    build:
      context: .
      dockerfile: tweets-backend/Dockerfile
    ports:
      - "8084:8084"

  accounts-db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  token-cache:
    image: redis:latest
    ports:
      - "6379:6379"

  tweets-db:
    image: mongo:latest
    command: --quiet
    ports:
      - "27018:27017"

  profiles-db:
    image: mongo:latest
    command: --quiet
    ports:
      - "27017:27017"