version: '3'

services:
  twote-frontend:
    build:
      context: ./twote-frontend
    ports:
      - "3000:3000"
    depends_on:
      - envoy-proxy

  envoy-proxy:
    image: envoyproxy/envoy:v1.18.3
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - twote-api

  twote-api:
    build:
      context: .
      dockerfile: twote-api/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      accounts-backend:
            condition: service_healthy
    volumes:
      - ./schemas:/usr/src/schemas

  accounts-backend:
    build:
      context: .
      dockerfile: accounts-backend/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./schemas:/usr/src/schemas

