[package]
name = "accounts-backend"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
schemas = { path = "../schemas" }
tracing.workspace=true
tracing-subscriber.workspace=true
common = { path = "../common" }
tonic.workspace=true
tonic-health.workspace=true
tokio.workspace=true