[package]
name = "twote-api"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
schemas = { path = "../schemas" }
tonic.workspace=true
tokio.workspace=true
tub.workspace=true
anyhow.workspace=true